# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14nk3cPdl572VW-pR6CghoG_SEOMPw-iD
"""

# Install Magnitude on Google Colab
! echo "Installing Magnitude.... (please wait, can take a while)"
! (curl https://raw.githubusercontent.com/plasticityai/magnitude/master/install-colab.sh | /bin/bash 1>/dev/null 2>/dev/null)
! echo "Done installing Magnitude."

from pymagnitude import *

file_path = "/content/drive/MyDrive/GoogleNews-vectors-negative300.magnitude"
vectors = Magnitude(file_path)

vectors.dim

vectors.most_similar(vectors.query("picnic"), topn = 6)

vectors.doesnt_match(["tissue", "papyrus", "manila", "newsprint", "parchment", "gazette"])

vectors.most_similar(positive = ["jump", "leg"], negative = ["throw"])

vectors.most_similar(positive = ["throw", "leg"], negative = ["jump"])